### ISSUE TITLE
scroll tabs also 

### ISSUE THREAD

**Issue by Anujmoglix** [zyra/ionic2-super-tabs-example#2]
HI , 
I have 7-10 tabs in my requirement so i want to scroll that tab also and don't want to crop my content too, 
I am attaching which i have done :- 
![selection_006](https://cloud.githubusercontent.com/assets/26056096/24895658/291ab5e6-1eaf-11e7-9e8d-8e7da54faeea.png)

Requirement like https://github.com/SinoThomas/Ionic2-ScrollableTabs  with your solution :)

**Comment by ihadeed** [comment]
Hey @Anujmoglix ,

The right place to discuss this would be at the project's repo here: https://github.com/zyra/ionic2-super-tabs

This feature is included in the upcoming 2.0 release, you can track the progress by subscribing to this issue here: https://github.com/zyra/ionic2-super-tabs/issues/14

Here's a GIF showing how it's looking so far, still needs one last fix and it should be good to go:

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/13794420/25010589/96589e54-2038-11e7-88d7-efa68b1f109c.gif)

**Comment by Anujmoglix** [comment]
Looking good ,Waiting for this ,Please do it :)

**Comment by cooldp007** [comment]
Hello, @ihadeed 
https://github.com/zyra/ionic2-super-tabs
I download your project from above link
but in that project there is no "pages" folder inside src folder

please help me.
